### ISSUE TITLE
Not able to connect with agent (aries-cloudagent-python)

### ISSUE THREAD

**Issue by proteche** [TimoGlastra/aries-mobile-agent-react-native#9]
when i'm trying to connect by passing invitaion url of `aries-cloudagent-python`  it stops  [here](https://github.com/TimoGlastra/aries-mobile-agent-react-native/blob/731f5b959c80d1afea00f6b9eddd1722fbbc47a4/src/App.tsx#L59)

**Mediator logs:**
```
aries-framework-javascript  error while unpacking message IndyError: 212
bob-mediator_1    |     at Object.callback (/www/node_modules/indy-sdk/src/wrapIndyCallback.js:15:10)
bob-mediator_1    | (node:40) UnhandledPromiseRejectionWarning: IndyError: 212
bob-mediator_1    |     at Object.callback (/www/node_modules/indy-sdk/src/wrapIndyCallback.js:15:10)
bob-mediator_1    | (node:40) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 23)
```
**steps to reproduce**

```
git clone https://github.com/hyperledger/aries-cloudagent-python
cd aries-cloudagent-python/demo
LEDGER_URL=http://dev.greenlight.bcovrin.vonx.io ./run_demo faber --events --no-auto --bg

http://0.0.0.0:8021/api/doc#/connection/post_connections_create_invitation
execute & get invitation url
```
 [more info (optional)](https://github.com/hyperledger/aries-cloudagent-python/blob/master/demo/AriesOpenAPIDemo.md)

**Comment by TimoGlastra** [comment]
can you share the response body of the create invitation call in ACA-Py? And did you start the mediator for the mobile wallet with or without ngrok?

Aries Framework JavaScript is tested to work with ACA-Py, so it should work

**Comment by proteche** [comment]
@TimoGlastra without ngrok & invitation object updated at the top.

**Comment by proteche** [comment]
@TimoGlastra In the logs i checked the endpoint is `"undefined:undefined/msg"`, (running without ngrok)
Mediator Logs 
```
bob-mediator_1    | 2020-12-09T20:33:46.907Z aries-framework-javascript ---------- outboundMessage ---------- 
bob-mediator_1    |  {
bob-mediator_1    |   "verkey": "EmSEx9XMmfdPrNMWng79ZvQYh8zAczaGgSqjiN11X81j",
bob-mediator_1    |   "theirKey": "2qLZZT2U5FvriKb85h2YdfzkmpWG5L3j5LCuT4NYNjYj",
bob-mediator_1    |   "routingKeys": [],
bob-mediator_1    |   "endpoint": "undefined:undefined/msg",
bob-mediator_1    |   "message": {
bob-mediator_1    |     "@type": "https://didcomm.org/messagepickup/1.0/batch",
bob-mediator_1    |     "@id": "e9601b91-9482-40eb-a1cc-43cd2f8b36d3",
bob-mediator_1    |     "messages~attach": []
bob-mediator_1    |   }
bob-mediator_1    | } 
```

**Comment by proteche** [comment]
@TimoGlastra can u tell me how to connect mediator with `aries-cloudagent-python ` or any steps to create connection between both.
